kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubesphere-preview
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      - containerPort: 30091
        hostPort: 30091
        protocol: TCP
      - containerPort: 30092
        hostPort: 30092
        protocol: TCP
      - containerPort: 30095
        hostPort: 30095
        protocol: TCP
    extraMounts:
      - hostPath: C:\Users\Administrator\Desktop\平台搭建\.runtime
        containerPath: /platform-runtime
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:30095"]
      endpoint = ["http://host.docker.internal:30095"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."host.docker.internal:30095".tls]
      insecure_skip_verify = true
