export interface PortalUiSurface {
  routeId: string;
  componentId: string;
  question: string;
  states: string[];
  selector: string;
  invariants: string[];
}

export interface PortalUiLayout {
  layoutId: string;
  purpose: string;
  slots: string[];
  selector: string;
  invariants: string[];
}

export const portalUiLayouts: PortalUiLayout[] = [
  {
    layoutId: "layout.app_shell",
    purpose: "承载 Portal 产品导航、普通用户和管理台视觉分区、页面标题和主内容区",
    slots: ["sidebar", "header", "main"],
    selector: '[data-layout-id="layout.app_shell"]',
    invariants: ["普通用户导航必须先于管理入口", "主内容区必须有稳定锚点", "shell 不得使用云控制台主语言"],
  },
  {
    layoutId: "layout.dashboard_page",
    purpose: "承载页面结论、指标和主要分区，让总览类页面先回答当前状态",
    slots: ["hero", "metrics", "primary", "secondary"],
    selector: '[data-layout-id="layout.dashboard_page"]',
    invariants: ["hero 必须先于指标出现", "页面级状态不得散落在业务组件外"],
  },
  {
    layoutId: "layout.table_page",
    purpose: "承载筛选、列表和分页，让列表类页面保持固定信息顺序",
    slots: ["header", "actions", "filters", "table", "pagination"],
    selector: '[data-layout-id="layout.table_page"]',
    invariants: ["filters 必须先于 table 出现", "pagination 必须独立于 table 内容"],
  },
  {
    layoutId: "layout.detail_page",
    purpose: "承载主详情和辅助信息，让详情类页面避免把所有面板堆在同一层",
    slots: ["primary", "secondary"],
    selector: '[data-layout-id="layout.detail_page"]',
    invariants: ["primary 承载主问题", "secondary 只能承载辅助解释或次级列表"],
  },
];

export const portalUiSurfaces: PortalUiSurface[] = [
  {
    routeId: "overview",
    componentId: "overview.hero",
    question: "用户买了什么托管科研工作台服务、当前是否可进入 OPL、如果受限下一步点哪里",
    states: ["loading", "ready", "restricted"],
    selector: '[data-component-id="overview.hero"]',
    invariants: [
      "首屏必须说明用户购买的是托管 OPL 科研工作台服务",
      "首屏必须展示环境、套餐、算力、存储和释放状态",
      "首屏必须给出唯一主下一步动作",
      "Portal 与 OPL runtime 职责边界必须在首屏可见",
    ],
  },
  {
    routeId: "overview",
    componentId: "overview.financial_metrics",
    question: "用户当前余额、冻结金额、消费和任务数量是什么",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="overview.financial_metrics"]',
    invariants: ["余额和冻结金额必须拆成独立指标", "累计消费必须独立展示"],
  },
  {
    routeId: "overview",
    componentId: "overview.managed_environment",
    question: "用户的托管运行环境、文件空间、冻结金额、释放和审计状态是否可用",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="overview.managed_environment"]',
    invariants: ["托管运行环境状态必须可见", "文件空间状态必须可见", "释放状态必须可见", "平台托管职责必须可见"],
  },
  {
    routeId: "overview",
    componentId: "overview.recent_runs",
    question: "输入文件如何进入任务，任务如何运行，输出结果如何回到工作空间",
    states: ["ready", "empty"],
    selector: '[data-component-id="overview.recent_runs"]',
    invariants: ["任务状态必须使用用户可理解文案", "分页动作必须稳定", "输入文件、任务运行和输出结果链路必须可见"],
  },
  {
    routeId: "overview",
    componentId: "overview.workspace",
    question: "用户的文件、任务和结果在哪里管理",
    states: ["ready", "empty"],
    selector: '[data-component-id="overview.workspace"]',
    invariants: ["工作空间入口必须可见", "内部资源标识不得展示", "文件进入工作空间和结果回到工作空间必须可见"],
  },
  {
    routeId: "overview",
    componentId: "overview.plans",
    question: "用户当前套餐、算力、存储和入门预计消费是什么",
    states: ["ready", "empty"],
    selector: '[data-component-id="overview.plans"]',
    invariants: ["套餐摘要必须独立于余额指标", "算力和存储摘要必须可见", "入门预计消费必须清晰标明估算"],
  },
  {
    routeId: "billing",
    componentId: "billing.hero",
    question: "用户当前余额、冻结金额、消费和账单核对状态是什么",
    states: ["loading", "ready", "restricted"],
    selector: '[data-component-id="billing.hero"]',
    invariants: ["余额、可用余额和冻结金额必须拆成独立指标", "导出入口必须保留"],
  },
  {
    routeId: "billing",
    componentId: "billing.cost_breakdown",
    question: "用户的钱花在计算、加速、文件空间和其他服务中的哪一类",
    states: ["ready", "degraded"],
    selector: '[data-component-id="billing.cost_breakdown"]',
    invariants: ["计算消费和文件空间消费必须独立展示", "账单回补状态必须可见"],
  },
  {
    routeId: "billing",
    componentId: "billing.trend_filter",
    question: "用户如何按日期查看账单窗口和成本趋势",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="billing.trend_filter"]',
    invariants: ["筛选窗口必须使用日期输入", "趋势为空时必须有空态"],
  },
  {
    routeId: "billing",
    componentId: "billing.workspace_costs",
    question: "各工作空间产生了多少任务和消费",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="billing.workspace_costs"]',
    invariants: ["移动端卡片和桌面表格必须同时存在", "工作空间成本分页必须稳定"],
  },
  {
    routeId: "billing",
    componentId: "billing.run_costs",
    question: "单次任务的状态、账单来源和总消费是什么",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="billing.run_costs"]',
    invariants: ["任务状态必须使用用户可理解文案", "任务成本分页必须稳定"],
  },
  {
    routeId: "billing",
    componentId: "billing.ledger",
    question: "用户账户流水里有哪些充值、资源扣费、退款和补扣",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="billing.ledger"]',
    invariants: ["账户流水必须独立于任务成本展示", "流水分页必须稳定"],
  },
  {
    routeId: "resources",
    componentId: "resources.hero",
    question: "用户当前租用的套餐、计算规格、文件空间、并发数和冻结金额状态是什么",
    states: ["loading", "ready", "degraded"],
    selector: '[data-component-id="resources.hero"]',
    invariants: ["计算规格和文件空间必须拆成独立指标", "预计费用必须清晰标明估算"],
  },
  {
    routeId: "resources",
    componentId: "resources.plan_selection",
    question: "用户可以查看哪些套餐并生成调整计划",
    states: ["ready", "empty"],
    selector: '[data-component-id="resources.plan_selection"]',
    invariants: ["套餐卡必须展示计算规格、文件空间、并发数和预计费用", "套餐选择不得真实开通资源"],
  },
  {
    routeId: "resources",
    componentId: "resources.adjustment",
    question: "用户如何生成计算资源或存储资源调整计划",
    states: ["ready", "restricted"],
    selector: '[data-component-id="resources.adjustment"]',
    invariants: ["调整动作必须标明 dry-run", "调整动作不得调用真实云"],
  },
  {
    routeId: "resources",
    componentId: "resources.current",
    question: "用户当前工作台资源是否可用，以及对应规格是什么",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="resources.current"]',
    invariants: ["当前资源状态必须可见", "内部资源标识不得展示"],
  },
  {
    routeId: "resources",
    componentId: "resources.release_audit",
    question: "用户释放资源后的停止计费和审计状态是什么",
    states: ["ready", "empty"],
    selector: '[data-component-id="resources.release_audit"]',
    invariants: ["停止计费和审计状态必须拆成独立字段", "释放策略不得显示云控制台叙事"],
  },
  {
    routeId: "trace",
    componentId: "trace.hero",
    question: "用户当前会话、任务、输出文件和费用估算概况是什么",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="trace.hero"]',
    invariants: ["运行记录必须优先于观测摘要", "费用估算必须标明不执行真实扣费"],
  },
  {
    routeId: "trace",
    componentId: "trace.filter",
    question: "用户如何按工作空间、会话和状态筛选运行轨迹",
    states: ["ready"],
    selector: '[data-component-id="trace.filter"]',
    invariants: ["筛选字段必须是用户可理解字段", "筛选动作不得暴露内部标识说明"],
  },
  {
    routeId: "trace",
    componentId: "trace.session_table",
    question: "用户如何查看会话、任务、文件、费用估算、状态和时间",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="trace.session_table"]',
    invariants: ["输入文件和输出文件必须拆成独立字段", "桌面表格和移动卡片必须都有空态"],
  },
  {
    routeId: "workspace",
    componentId: "workspace.hero",
    question: "用户如何进入 OPL 工作台、查看当前工作空间状态和关键文件指标",
    states: ["loading", "ready", "restricted"],
    selector: '[data-component-id="workspace.hero"]',
    invariants: ["OPL 工作台入口必须可见", "输入文件、输出文件和任务数必须独立展示"],
  },
  {
    routeId: "workspace",
    componentId: "workspace.file_space",
    question: "用户如何管理文件夹、选择文件、上传下载和理解保护期",
    states: ["ready", "empty", "restricted"],
    selector: '[data-component-id="workspace.file_space"]',
    invariants: ["文件空间状态必须可见", "危险操作必须和普通文件操作分离"],
  },
  {
    routeId: "workspace",
    componentId: "workspace.managed_plan",
    question: "用户如何查看托管运行环境计划、费用估算、释放策略和审计状态",
    states: ["ready", "empty"],
    selector: '[data-component-id="workspace.managed_plan"]',
    invariants: ["计划快照必须标明不代表真实资源已创建", "停止计费和审计状态必须拆分展示"],
  },
  {
    routeId: "workspace",
    componentId: "workspace.list",
    question: "用户如何浏览多个工作空间及其文件、任务和状态",
    states: ["ready", "empty"],
    selector: '[data-component-id="workspace.list"]',
    invariants: ["列表页必须提供桌面表格和移动卡片", "分页必须独立于表格内容"],
  },
  {
    routeId: "workspace",
    componentId: "workspace.files",
    question: "用户如何查看和下载当前工作空间的输入文件与输出文件",
    states: ["ready", "empty", "restricted"],
    selector: '[data-component-id="workspace.files"]',
    invariants: ["输入文件和输出文件必须拆成独立面板", "上传行为必须保持表单边界"],
  },
  {
    routeId: "admin.system",
    componentId: "admin.system.site_settings",
    question: "管理员如何配置站点名称、站点 logo、首页内容和注册开关",
    states: ["loading", "ready", "saving", "error"],
    selector: '[data-component-id="admin.system.site_settings"]',
    invariants: ["站点 logo 必须支持预览", "首页内容必须保留代码编辑框"],
  },
  {
    routeId: "admin.system",
    componentId: "admin.system.service_status",
    question: "管理员如何查看 Portal 主链路服务状态",
    states: ["ready", "empty"],
    selector: '[data-component-id="admin.system.service_status"]',
    invariants: ["服务状态必须与站点设置分离", "服务异常数量必须独立展示"],
  },
  {
    routeId: "admin.dashboard",
    componentId: "admin.dashboard.summary",
    question: "管理员如何查看平台今日用户、工作空间、任务、消费和待处理事项",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="admin.dashboard.summary"]',
    invariants: ["平台总览必须先展示指标", "管理入口不能使用云控制台叙事"],
  },
  {
    routeId: "admin.users",
    componentId: "admin.users.table",
    question: "管理员如何搜索客户账户并执行开通、禁用、充值和退款动作",
    states: ["loading", "ready", "empty", "error"],
    selector: '[data-component-id="admin.users.table"]',
    invariants: ["客户账户和资金动作必须同页可见", "内部编号只能作为排障辅助字段"],
  },
  {
    routeId: "admin.billing_ops",
    componentId: "admin.billing_ops.summary",
    question: "管理员如何查看账单对账、待补记录、成本构成和最近调整",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="admin.billing_ops.summary"]',
    invariants: ["账单管理必须使用账单命名", "待补记录和最近调整必须分开展示"],
  },
  {
    routeId: "admin.usage",
    componentId: "admin.usage.table",
    question: "管理员如何查看任务记录、运行状态、成本和下钻入口",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="admin.usage.table"]',
    invariants: ["任务状态必须映射成中文", "成本必须独立于运行编号展示"],
  },
  {
    routeId: "admin.audit",
    componentId: "admin.audit.table",
    question: "管理员如何查看审计记录、事件来源、操作人和工作空间归属",
    states: ["loading", "ready", "empty"],
    selector: '[data-component-id="admin.audit.table"]',
    invariants: ["审计事件必须使用中文类型", "筛选和分页必须独立于表格内容"],
  },
];

export const portalUiSurfaceSelectors = portalUiSurfaces.map((surface) => surface.selector);
