apiVersion: v1
kind: Secret
metadata:
  name: secret-portal
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  PORTAL_ADMIN_EMAIL: "zitadel-admin@zitadel.localhost"
  PORTAL_ADMIN_NAME: "Admin"
  PORTAL_ADMIN_PASSWORD: "PortalAdmin-TKE-2026-ChangeThis!"
  PORTAL_OIDC_CLIENT_SECRET: ""
  PORTAL_INTERNAL_AUTH_TOKEN: "OOVu7jTho1KmOPio5PPd4XramkaBs6jhlC3xyiBYA6qAAarclfPJh8JXG1TGrSFP"
  HARBOR_USERNAME: "100047070895"
  HARBOR_PASSWORD: "DEde0124@@.."
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-opl
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  OPL_LAUNCH_SECRET: "UHmRvW5bBLUdsYlq2I7Oz26_PiyphLmKeZp-fsp0Rrm9ZPVvdHuYPbGlqrdiOJM9"
  OPL_ACP_RUNTIME_COMMAND_JSON: ""
  MED_AUTOSCIENCE_RUNNER_TOKEN: "WfMLeWwNL9FjSNYIiPIubqoH7a_8L2cOGzx3fVn_0vTQm0wgkiBlz8GLduqlL9xc"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-trace
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-postgres-redis-secret
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  PORTAL_POSTGRES_URL: "postgresql://gaofenglab:GaoFengLab%402019_now@10.0.0.139:5432/postgres?sslmode=disable"
  PORTAL_REDIS_URL: "redis://:GaoFengLab%402019_now@10.0.0.141:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: tencent-billing-secret
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  TENCENT_BILLING_SECRET_ID: "AKIDhMp45sRnwqXzCF6i6IHi6IFzUklYDfuu"
  TENCENT_BILLING_SECRET_KEY: "pqfHfoiOq43rgHgroXv50h9MK6i5D7pY"
  TENCENT_CLOUD_TOKEN: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: tencent-provisioner-secret
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  TENCENT_BILLING_SECRET_ID: "AKIDhMp45sRnwqXzCF6i6IHi6IFzUklYDfuu"
  TENCENT_BILLING_SECRET_KEY: "pqfHfoiOq43rgHgroXv50h9MK6i5D7pY"
  TENCENT_CLOUD_TOKEN: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: tencent-cos-secret
  namespace: portal-v20-32-staging
type: Opaque
stringData:
  TENCENT_COS_SECRET_ID: "AKIDTs30jFYdU7yk8MNFpEPL3WllY6SdaIkA"
  TENCENT_COS_SECRET_KEY: "a6UhgQwFJ7gF1e2CCCzYv521tfKxV0Oa"
