apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-platform-runtime
  namespace: portal-v20-32-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "cfs-rwx"
  resources:
    requests:
      storage: "20Gi"

