apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-cluster-store
spec:
  provider:
    vault:
      server: http://openbao.openbao-system.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: openbao-eso-token
          key: token
          namespace: external-secrets
