apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workspace-runtime-secrets
  namespace: med-agent-demo
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-store
  target:
    name: workspace-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_PULL_USERNAME
      remoteRef:
        key: platform/harbor
        property: username
    - secretKey: HARBOR_PULL_PASSWORD
      remoteRef:
        key: platform/harbor
        property: password
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: platform/minio
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: platform/minio
        property: secret_key
