apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portal-platform-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-store
  target:
    name: portal-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: PORTAL_OIDC_CLIENT_SECRET
      remoteRef:
        key: platform/portal
        property: oidc_client_secret
    - secretKey: PORTAL_ADMIN_PASSWORD
      remoteRef:
        key: platform/portal
        property: admin_password
    - secretKey: BILLING_SIGNING_KEY
      remoteRef:
        key: platform/billing
        property: signing_key
