apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openbao-local-probe
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-local-dev-store
  target:
    name: openbao-local-probe
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: local/probe
        property: value
