apiVersion: v1
kind: Secret
metadata:
  name: openbao-eso-token
  namespace: external-secrets
type: Opaque
stringData:
  token: root
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-local-dev-store
spec:
  provider:
    vault:
      server: http://openbao.openbao-system.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: openbao-eso-token
          key: token
          namespace: external-secrets
