server:
  replicas: 1
  dev:
    enabled: true
    devRootToken: "root"
  ha:
    enabled: false
  standalone:
    enabled: false
  dataStorage:
    enabled: false
  auditStorage:
    enabled: false
injector:
  enabled: true
ui:
  enabled: true
