apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-platform-runtime
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "__RUNTIME_STORAGE_CLASS__"
  resources:
    requests:
      storage: "__RUNTIME_STORAGE_SIZE__"

