import { createWorkspaceUploadSupport } from "./workspace-storage-upload-support.mjs";
import { createWorkspaceStorageRouteHandler } from "./workspace-storage-route-handlers.mjs";
import { safeRelativePath as strictSafeRelativePath } from "../domain/workspace-storage.mjs";

export function createWorkspaceStorageRoutes({
  buildWorkspaceFileChecksum,
  buildWorkspaceStorageKey,
  createOrUpdateStorageOrder,
  defaultTaskTitle,
  ensureTaskSpace,
  exists,
  fetchWorkspaceUserStorageState,
  fetchWorkspaceStorageSnapshot,
  findTaskSpace,
  guessContentType,
  issueWorkspaceTransferToken,
  listWorkspaceFiles,
  logPortalEvent,
  path,
  readBody,
  readDb,
  readWorkspaceTransferToken,
  recordWorkspaceFile,
  safeRelativePath,
  sendFile,
  sendJson,
  slugify,
  stat,
  mkdir,
  syncWorkspaceFileToUserStorage,
  workspaceStorageEntitlement,
  writeFile,
  writeDb,
}) {
  void safeRelativePath;
  const uploadSupport = createWorkspaceUploadSupport({
    buildWorkspaceFileChecksum,
    buildWorkspaceStorageKey,
    guessContentType,
    mkdir,
    path,
    recordWorkspaceFile,
    safeRelativePath: strictSafeRelativePath,
    stat,
    syncWorkspaceFileToUserStorage,
    writeFile,
  });

  return createWorkspaceStorageRouteHandler({
    buildWorkspaceStorageKey,
    createOrUpdateStorageOrder,
    defaultTaskTitle,
    ensureTaskSpace,
    exists,
    fetchWorkspaceUserStorageState,
    fetchWorkspaceStorageSnapshot,
    findTaskSpace,
    guessContentType,
    issueWorkspaceTransferToken,
    listWorkspaceFiles,
    logPortalEvent,
    path,
    persistWorkspaceUpload: uploadSupport.persistWorkspaceUpload,
    readBody,
    readDb,
    readMultipartFiles: uploadSupport.readMultipartFiles,
    readWorkspaceTransferToken,
    safeRelativePath: strictSafeRelativePath,
    sendFile,
    sendJson,
    slugify,
    workspaceStorageEntitlement,
    writeDb,
  });
}
